name       : bubblewrap
version    : 0.4.0
release    : 7
source     :
    - https://github.com/containers/bubblewrap/releases/download/v0.4.0/bubblewrap-0.4.0.tar.xz : e5fe7d2f74bd7029b5306b0b70587cec31f74357739295e5276b4a3718712023
license    : LGPL-2.0-or-later
component  : security
summary    : Unprivileged sandboxing tool
description: |
    Unprivileged sandboxing tool
builddeps  :
    - pkgconfig(bash-completion)
    - pkgconfig(libcap)
    - docbook-xml
setup      : |
    %configure  --with-priv-mode=setuid
build      : |
    %make
install    : |
    %make_install
