name       : bubblewrap
version    : 0.2.1
release    : 3
source     :
    - https://github.com/projectatomic/bubblewrap/releases/download/v0.2.1/bubblewrap-0.2.1.tar.xz : 54b8c805b0ed5c961f6975589c7343b9c3bf1a8987e1593683c670edeee31fe2
license    : LGPL-2.0-or-later
component  : security
summary    : Unprivileged sandboxing tool
description: |
    Unprivileged sandboxing tool
builddeps  :
    - pkgconfig(bash-completion)
    - pkgconfig(libcap)
    - docbook-xml
setup      : |
    %configure  --with-priv-mode=setuid
build      : |
    %make
install    : |
    %make_install
