name       : bubblewrap
version    : 0.3.0
release    : 4
source     :
    - https://github.com/projectatomic/bubblewrap/releases/download/v0.3.0/bubblewrap-0.3.0.tar.xz : c8e52870b54a10235174775e03164b2a9253e19cb3a95b3e4bd9e2d84b9eaf2c
license    : LGPL-2.0-or-later
component  : security
summary    : Unprivileged sandboxing tool
description: |
    Unprivileged sandboxing tool
builddeps  :
    - pkgconfig(bash-completion)
    - pkgconfig(libcap)
    - docbook-xml
setup      : |
    %configure  --with-priv-mode=setuid
build      : |
    %make
install    : |
    %make_install
