name       : bubblewrap
version    : 0.6.0
release    : 13
source     :
    - https://github.com/containers/bubblewrap/releases/download/v0.6.0/bubblewrap-0.6.0.tar.xz : 11393cf2058f22e6a6c6e9cca3c85ff4c4239806cb28fee657c62a544df35693
license    : LGPL-2.0-or-later
component  : security
homepage   : https://github.com/containers/bubblewrap/
summary    : Unprivileged sandboxing tool
description: |
    Unprivileged sandboxing tool
builddeps  :
    - pkgconfig(bash-completion)
    - pkgconfig(libcap)
    - docbook-xml
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
