name       : bubblewrap
version    : 0.1.8
release    : 1
source     :
    - https://github.com/projectatomic/bubblewrap/releases/download/v0.1.8/bubblewrap-0.1.8.tar.xz : 4c1c7f71821e378ac3800de6c1124ed267844a4849f95e557f2e378ed53ddebf
license    : LGPL-2.0
component  : security
summary    : Unprivileged sandboxing tool
description: |
    Unprivileged sandboxing tool
builddeps  :
    - pkgconfig(bash-completion)
    - pkgconfig(libcap)
    - docbook-xml
setup      : |
    %configure  --prefix=/usr \
                --with-priv-mode=setuid
build      : |
    %make
install    : |
    %make_install
