name       : bubblewrap
version    : 0.3.1
release    : 5
source     :
    - https://github.com/projectatomic/bubblewrap/releases/download/v0.3.1/bubblewrap-0.3.1.tar.xz : deca6b608c54df4be0669b8bb6d254858924588e9f86e116eb04656a3b6d4bf8
license    : LGPL-2.0-or-later
component  : security
summary    : Unprivileged sandboxing tool
description: |
    Unprivileged sandboxing tool
builddeps  :
    - pkgconfig(bash-completion)
    - pkgconfig(libcap)
    - docbook-xml
setup      : |
    %configure  --with-priv-mode=setuid
build      : |
    %make
install    : |
    %make_install
