name       : bubblewrap
version    : 0.2.0
release    : 2
source     :
    - https://github.com/projectatomic/bubblewrap/releases/download/v0.2.0/bubblewrap-0.2.0.tar.xz : ccb61a3718b927765dafd3587c5b619d28c39a3f8b05a4b41e93b2fb2c181c2a
license    : LGPL-2.0
component  : security
summary    : Unprivileged sandboxing tool
description: |
    Unprivileged sandboxing tool
builddeps  :
    - pkgconfig(bash-completion)
    - pkgconfig(libcap)
    - docbook-xml
setup      : |
    %configure  --with-priv-mode=setuid
build      : |
    %make
install    : |
    %make_install
