name       : bubblewrap
version    : 0.3.3
release    : 6
source     :
    - https://github.com/containers/bubblewrap/releases/download/v0.3.3/bubblewrap-0.3.3.tar.xz : c6a45f51794a908b76833b132471397a7413f07620af08e76c273d9f7b364dff
license    : LGPL-2.0-or-later
component  : security
summary    : Unprivileged sandboxing tool
description: |
    Unprivileged sandboxing tool
builddeps  :
    - pkgconfig(bash-completion)
    - pkgconfig(libcap)
    - docbook-xml
setup      : |
    %configure  --with-priv-mode=setuid
build      : |
    %make
install    : |
    %make_install
