name       : bubblewrap
version    : 0.5.0
release    : 12
source     :
    - https://github.com/containers/bubblewrap/releases/download/v0.5.0/bubblewrap-0.5.0.tar.xz : 16fdaf33799d63104e347e0133f909196fe90d0c50515d010bcb422eb5a00818
license    : LGPL-2.0-or-later
component  : security
homepage   : https://github.com/containers/bubblewrap/
summary    : Unprivileged sandboxing tool
description: |
    Unprivileged sandboxing tool
builddeps  :
    - pkgconfig(bash-completion)
    - pkgconfig(libcap)
    - docbook-xml
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
