name       : bubblewrap
version    : 0.4.1
release    : 11
source     :
    - https://github.com/containers/bubblewrap/releases/download/v0.4.1/bubblewrap-0.4.1.tar.xz : b9c69b9b1c61a608f34325c8e1a495229bacf6e4a07cbb0c80cf7a814d7ccc03
license    : LGPL-2.0-or-later
component  : security
homepage   : https://github.com/containers/bubblewrap/
summary    : Unprivileged sandboxing tool
description: |
    Unprivileged sandboxing tool
builddeps  :
    - pkgconfig(bash-completion)
    - pkgconfig(libcap)
    - docbook-xml
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
